import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { mkdtemp } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test, { after } from "node:test";
import { fileURLToPath } from "node:url";

// `scripts/commit.sh` lets a commit through a tree that has the private crate
// swapped in, by restoring the stub for the length of one `git commit`.
//
// The failure it has to prevent is specific and is NOT the one the commit hook
// already handles. `check-no-private.sh` looks at the working tree and refuses
// when the STUB marker is gone. This script's whole method is to make the
// working tree be the stub — restored from the INDEX — before the hook runs. So
// a private source somebody staged would be written into the tree by that very
// restore, the marker would be present, and the hook would pass it.
//
// The hook is not wrong. It was never asked about the index. These tests pin
// that the script asks, and — just as importantly — that asking does not turn
// into refusing everything: a public placeholder under the same path is exactly
// what a new seam needs, and must still go through.

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const realScript = path.join(repoRoot, "scripts/commit.sh");
const realGuard = path.join(repoRoot, "scripts/check-no-private.sh");

const tempDirs = [];
after(() => {
  for (const dir of tempDirs) rmSync(dir, { recursive: true, force: true });
});

const CLEAN_LOCK = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "sealwire-private"
version = "0.1.0"
`;

const STUB_MODULE = `// Public-checkout placeholder.
export function Thing() {
  return null;
}
`;

const PRIVATE_MODULE = `// The real thing, which must never reach a public commit.
export function Thing() {
  return computeSomethingProprietary();
}
`;

function git(cwd, ...args) {
  const res = spawnSync("git", args, { cwd, encoding: "utf8" });
  assert.equal(res.status, 0, `git ${args.join(" ")} failed: ${res.stderr}`);
  return res.stdout;
}

/** A miniature public checkout: stub crate + marker, clean lock, real scripts, real hook. */
async function makeFixture() {
  const root = await mkdtemp(path.join(os.tmpdir(), "commit-swapped-"));
  tempDirs.push(root);
  const repo = path.join(root, "repo");
  const priv = path.join(root, "sealwire-private");

  mkdirSync(path.join(repo, "crates/sealwire-private/frontend"), { recursive: true });
  mkdirSync(path.join(repo, "frontend"), { recursive: true });
  mkdirSync(path.join(repo, "scripts"), { recursive: true });
  writeFileSync(path.join(repo, "crates/sealwire-private/STUB"), "stub marker\n");
  writeFileSync(path.join(repo, "crates/sealwire-private/frontend/thing.js"), STUB_MODULE);
  writeFileSync(path.join(repo, "Cargo.lock"), CLEAN_LOCK);
  writeFileSync(path.join(repo, "frontend/app.js"), "// public\n");
  cpSync(realScript, path.join(repo, "scripts/commit.sh"));
  cpSync(realGuard, path.join(repo, "scripts/check-no-private.sh"));

  git(repo, "init", "-q");
  git(repo, "-c", "core.hooksPath=/dev/null", "add", "-A");
  git(repo, "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-q", "-m", "init", "--no-verify");

  // The real hook, so the guard genuinely runs during these tests.
  writeFileSync(
    path.join(repo, ".git/hooks/pre-commit"),
    '#!/bin/sh\nexec "$(git rev-parse --show-toplevel)/scripts/check-no-private.sh"\n',
    { mode: 0o755 }
  );

  mkdirSync(path.join(priv, "frontend"), { recursive: true });
  writeFileSync(path.join(priv, "frontend/thing.js"), PRIVATE_MODULE);
  writeFileSync(path.join(priv, "frontend/only-private.js"), "// no stub exists for this\n");

  return { root, repo, priv };
}

/** Put the tree in the state `npm run dev:full` leaves it in: private sources, no marker. */
function swapIn(repo, priv) {
  const target = path.join(repo, "crates/sealwire-private");
  rmSync(target, { recursive: true, force: true });
  cpSync(priv, target, { recursive: true });
  assert.ok(!existsSync(path.join(target, "STUB")), "fixture: swapped tree still has STUB");
}

function commit(repo, priv, args = ["-m", "msg"]) {
  return spawnSync("bash", [path.join(repo, "scripts/commit.sh"), ...args], {
    cwd: repo,
    encoding: "utf8",
    env: {
      ...process.env,
      RELAY_PRIVATE_PATH: priv,
      GIT_AUTHOR_NAME: "t",
      GIT_AUTHOR_EMAIL: "t@t",
      GIT_COMMITTER_NAME: "t",
      GIT_COMMITTER_EMAIL: "t@t",
    },
  });
}

const head = (repo) => git(repo, "log", "--oneline").trim().split("\n").length;

test("a public change commits while the tree is swapped, and the swap survives it", async () => {
  const { repo, priv } = await makeFixture();
  swapIn(repo, priv);
  writeFileSync(path.join(repo, "frontend/app.js"), "// public, edited\n");
  git(repo, "add", "frontend/app.js");

  const res = commit(repo, priv);
  assert.equal(res.status, 0, `expected success: ${res.stderr}`);
  assert.equal(head(repo), 2, "the commit was created");

  // The private sources are back, and the marker is still absent — the tree is
  // as `dev:full` left it. Without this the script would silently un-swap a
  // running dev server, and the next frontend build would ship placeholders.
  const target = path.join(repo, "crates/sealwire-private");
  assert.equal(readFileSync(path.join(target, "frontend/thing.js"), "utf8"), PRIVATE_MODULE);
  assert.ok(existsSync(path.join(target, "frontend/only-private.js")), "private-only module survived");
  assert.ok(!existsSync(path.join(target, "STUB")), "the tree is still swapped");
});

test("the swap is restored even when the commit fails", async () => {
  // The restore runs from a trap, so it has to cover the paths that are not the
  // happy one. An empty commit is the cheapest way to make git refuse after the
  // stub is already in place — the window where a missing trap strands the tree.
  const { repo, priv } = await makeFixture();
  swapIn(repo, priv);

  const res = commit(repo, priv);
  assert.notEqual(res.status, 0, "an empty commit should fail");

  const target = path.join(repo, "crates/sealwire-private");
  assert.equal(readFileSync(path.join(target, "frontend/thing.js"), "utf8"), PRIVATE_MODULE);
  assert.ok(!existsSync(path.join(target, "STUB")), "a failed commit still leaves the swap in place");
});

test("staging the private source itself is refused", async () => {
  // The hole this script exists to close. The file is staged under the crate
  // path with the private CONTENT; restoring the index would hand the hook a
  // tree with an intact STUB marker, and the hook would pass it.
  const { repo, priv } = await makeFixture();
  swapIn(repo, priv);
  git(repo, "add", "crates/sealwire-private/frontend/thing.js");

  const res = commit(repo, priv);
  assert.notEqual(res.status, 0, "the private source must not be committable");
  assert.match(res.stderr, /is the private source itself/);
  assert.equal(head(repo), 1, "no commit was created");
});

test("a public placeholder under the same path still commits", async () => {
  // The control, and the reason the check compares CONTENT rather than refusing
  // the path. "Refuses the private source" is also true of a script that refuses
  // everything under that directory — which would block every new seam, since
  // each one needs a placeholder committed there.
  const { repo, priv } = await makeFixture();
  swapIn(repo, priv);
  // Stage a placeholder for a module that exists only on the private side.
  const blob = spawnSync("git", ["hash-object", "-w", "--stdin"], {
    cwd: repo,
    input: "// Public-checkout placeholder.\nexport const nothing = null;\n",
    encoding: "utf8",
  }).stdout.trim();
  git(
    repo,
    "update-index",
    "--add",
    "--cacheinfo",
    `100644,${blob},crates/sealwire-private/frontend/only-private.js`
  );

  const res = commit(repo, priv);
  assert.equal(res.status, 0, `a placeholder must be committable: ${res.stderr}`);
  assert.equal(head(repo), 2);
  assert.match(
    git(repo, "show", "HEAD:crates/sealwire-private/frontend/only-private.js"),
    /placeholder/
  );
});

test("a lock poisoned by a swapped build is committed clean and left poisoned", async () => {
  // Two halves. The hook refuses a lock carrying the private crate's
  // dependencies, so the commit has to record the clean one; but the running
  // dev server's tree should be handed back exactly as it was found.
  const { repo, priv } = await makeFixture();
  swapIn(repo, priv);
  const poisoned = CLEAN_LOCK.replace(
    'version = "0.1.0"\n',
    'version = "0.1.0"\ndependencies = [\n "closed-dep",\n]\n'
  );
  writeFileSync(path.join(repo, "Cargo.lock"), poisoned);
  writeFileSync(path.join(repo, "frontend/app.js"), "// edited\n");
  git(repo, "add", "frontend/app.js");

  const res = commit(repo, priv);
  assert.equal(res.status, 0, `expected success: ${res.stderr}`);
  assert.equal(git(repo, "show", "HEAD:Cargo.lock"), CLEAN_LOCK, "the commit records the clean lock");
  assert.equal(readFileSync(path.join(repo, "Cargo.lock"), "utf8"), poisoned, "the tree is handed back as found");
});

test("an unswapped tree is passed straight through to git commit", async () => {
  const { repo, priv } = await makeFixture();
  writeFileSync(path.join(repo, "frontend/app.js"), "// edited\n");
  git(repo, "add", "frontend/app.js");

  const res = commit(repo, priv);
  assert.equal(res.status, 0, `expected success: ${res.stderr}`);
  assert.equal(head(repo), 2);
  assert.ok(existsSync(path.join(repo, "crates/sealwire-private/STUB")), "the stub was never disturbed");
});
